#!/bin/sh

_deadbeef(){ local stopped=false
  _read_arg
  [ "$_GET_action" = "pause" ] && _GET_action="play-pause"
  deadbeef "--$_GET_action" 2>/dev/null; sleep 0.2
  [ "$(deadbeef --nowplaying "%a")" = "nothing" ] && stopped=true
  _reply "
    <style>
      body { background: black; }
      #player { background: #111; border-radius: 5px; font-family: monospace; font-size: 10px; color: #FFF; padding: 3px; }
      #path { display: block }
      #artist:after { content:\" - \" } #path { color:#DDD; }
      a:link, a:active, a:visited {color:#FFF} a:hover {color:#AFF}
    </style>
    <div id=player>
      <div id=info>
        <span id=artist>$(deadbeef --nowplaying "%a" 2>/dev/null)</span>
        <span id=title>$(deadbeef --nowplaying "%t" 2>/dev/null)</span>
        <span id=path>$(deadbeef --nowplaying "%F" 2>/dev/null)</span>
      </div>
      $($stopped || echo "<a id=prev href=\"?action=prev\">prev</a>")
      <a id=pause href=\"?action=pause\">pause</a>
      <a id=stop href=\"?action=stop\">stop</a>
      <a id=random href=\"?action=random\">random</a>
      <a id=next href=\"?action=next\">next</a>
    </div>
  "; }

_deadbeef $@